sudo: required
services:
  - docker

before_install:
  - docker build -t decentralized-voting/frontend -f /decentralized-voting/frontend/Dockerfile.dev

script:
  - docker run decentralized-voting/frontend npm run test -- --coverage
